name: Terraform Checks

on:
  pull_request:
    branches: [ "main" ]

jobs:
  terraform-checks:
    runs-on: ubuntu-latest
    env:                             # 👈 set globally here
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform fmt check
        run: terraform fmt -check -recursive
      - name: Terraform validate
        run: terraform validate
      - name: Terraform init
        run: terraform init
      - name: Terraform plan (check only)
        run: terraform plan
